---

- name: Configure SELinux to permit outgoing connections
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Deploy endpoints
  template:
    src: endpoint.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
  with_items: '{{ nginx_reverse_endpoints }}'
  notify:
    - restart nginx
